SELECT * FROM MAXUSERGROUPS WHERE GRPNAME LIKE '%PD%';

SELECT * FROM MAXUSERGROUPS WHERE USRNAME LIKE '%EBAKOUSH%';

SELECT * FROM MAXUSERGROUPS WHERE USRNAME='SALAHS';

SELECT * FROM MAXUSERGROUPS WHERE GRPNAME='MELMSPS';


--DELETE FROM MAXUSERSTATUS WHERE USERNAME='SALAHS';

--DELETE FROM MAXUSERGROUPS WHERE USRNAME='SALAHS';
