SELECT tablespace_name, file_name, BYTES  FROM dba_temp_files
 WHERE tablespace_name LIKE 'TEMP%';


---DROP TABLESPACE temp0 INCLUDING CONTENTS AND DATAFILES;
ALTER    DATABASE DEFAULT TEMPORARY TABLESPACE temp0;



CREATE TEMPORARY TABLESPACE temp0
   TEMPFILE 'F:\ORACLE\ORADATA\HQMAIN\TEMP0.DBF' SIZE 5000 m 
   AUTOEXTEND ON NEXT 128 m MAXSIZE UNLIMITED
   EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m;
